[package]
name = "pubky-noise"
description = "Fully-integrated Noise AE framework in pubky-sdk"
version = "0.1.0-rc8"
edition = "2021"
rust-version = "1.89"
license = "MIT"
repository = "https://github.com/pubky/pubky-noise"
keywords = ["pubky", "noise"]
categories = ["cryptography"]

[features]
test-utils = []

[dependencies]
pubky = "0.11.0"
ed25519-dalek = "3.0.0"
curve25519-dalek = "5.0.0"
snow = { version = "0.10.0", features = ["use-sha2"] }
getrandom = "0.3"
sha2 = "0.11.0"
hex = "0.4"
rand = "0.9.0"
