name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.93
          components: rustfmt
          override: true
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.93
          components: rustfmt
          override: true
      - name: Check formatting
        run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.93
          components: clippy
          override: true
      - name: Check clippy
        run: cargo clippy -p pubky-noise

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.93
          override: true
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Install Nextest
        uses: taiki-e/install-action@nextest
      - name: Unit tests
        run: cargo nextest run -p pubky-noise

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.93
          override: true
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Install Nextest
        uses: taiki-e/install-action@nextest
      - name: E2E tests
        run: cargo nextest run -p e2e
